### ISSUE TITLE
Create `Range Slider` Component 

### ISSUE THREAD

**Issue by sohamsshah** [moja-global/FLINT-UI#110] opened 2021-11-14 17:11 UTC
### Is your feature request related to a problem? Please describe.

According to the new design update, we are aiming to develop an updated version for Slider Component. 
Currently our slider component looks something like:

![image](https://user-images.githubusercontent.com/47717492/141690843-86766ec3-252c-4a0a-964a-1a584a0cc8eb.png)

### Describe the solution you'd like.

We want to create new component like this (with tailwind css):
![image](https://user-images.githubusercontent.com/47717492/141690820-6bd2f72c-0e33-41a4-a46b-23f5c69fd93d.png)

### Describe alternatives you've considered

The current slider component lies in `flint.ui/src/components/Sliders`. The new Slider Component should be added in this folder (no need to delete other component files.) Test this by updating the views on `/flint/configurations/point` etc. routes to ensure working of the component.

### Additional context.

Make sure the component:
- Uses Tailwind CSS utility classes (feel free to update `tailwind.config.js` file to extend new theme if needed(
- Is accessible and without any logical errors
- Thoroughly tested on different routes where the older Slider Component was used

Feel Free to ask questions or curiosities around its implementation.

**Comment by anjali1102** [comment] 2021-11-15 13:43
Kindly assign me

**Comment by chicken-biryani** [comment] 2021-11-15 13:43
Go ahead, @anjali1102 !

**Comment by Marob-nod** [comment] 2021-11-15 14:29
Hi ! Is this issue already assigned ? Or can i work on it ?

**Comment by sohamsshah** [comment] 2021-12-04 12:06
Hey @anjali1102 , Do you have any progress on this? If timing is bad for you, maybe I should un-assign you so someone else can take this?

**Comment by anjali1102** [comment] 2021-12-05 07:22
Hey @sohamsshah  sorry for being late, i'll surely finish it by today

**Comment by anjali1102** [comment] 2021-12-05 12:56
hi @sohamsshah 
I did these changes 
![1](https://user-images.githubusercontent.com/56559378/144747395-7f773fa7-4c0a-4f09-8365-09ded8e7bedb.PNG)
![2](https://user-images.githubusercontent.com/56559378/144747398-430b3b56-a5ad-40f9-a1ed-d813a490d602.PNG)

I am unable to see any changes on my localhost or http://127.0.0.1:8000/flint/configurations/point


I set up  by following Development notes in readme here
![3](https://user-images.githubusercontent.com/56559378/144747432-6f10fd8b-0774-4184-befe-c61005126350.PNG)

**Comment by sohamsshah** [comment] 2021-12-15 16:03
Hi @anjali1102 , are you working on this? If it is not a good time for you at the moment, please feel free to let us know 😊

**Comment by yashsehgal** [comment] 2021-12-16 05:14
Hey @chicken-biryani @sohamsshah I would like to work on this issue if no one's working on it. 😄

**Comment by sohamsshah** [comment] 2021-12-16 05:38
@yashsehgal , sure go ahead! I would suggest lets brainstorm a bit on what props can be added for our implementation of Range Slider component. We can refer some popular design systems to decide them.

**Comment by yashsehgal** [comment] 2021-12-16 06:02
Yeah sure @sohamsshah I will create and share a list of features we can add to this component, according to our requirements.

**Comment by chicken-biryani** [comment] 2021-12-16 06:42
@sohamsshah @yashsehgal 

Could we replace the range slider with text boxes?

Because-

1) The range slider limits the users. To give the range from 0 to 400. Whereas the value of the pools can go way beyond.

2) Precicion is not met with range slider. A lot of times the value of pools are in float/decimal values.


Just a thought. I think putting a text box would be better.

Or maybe we could keep the range slider and put a text box below that.

Cc: @shubhamkarande13

**Comment by yashsehgal** [comment] 2021-12-16 07:03
> @sohamsshah @yashsehgal 
> 
> Could we replace the range slider with text boxes?
> 
> Because-
> 
> 1) The range slider limits the users. To give the range from 0 to 400. Whereas the value of the pools can go way beyond.
> 
> 2) Precicion is not met with range slider. A lot of times the value of pools are in float/decimal values.
> 
> 
> Just a thought. I think putting a text box would be better.
> 
> Or maybe we could keep the range slider and put a text box below that.
> 
> Cc: @shubhamkarande13 

Great idea. What we do is create a component wrapper with 2 radio based options (custom and range) so that by default users can set a range value, if they want custom then after selecting the custom radio button an input box will appear.

If this sounds to be a good approach, I can start designing it.

**Comment by sohamsshah** [comment] 2021-12-16 07:43
> > @sohamsshah @yashsehgal
> > Could we replace the range slider with text boxes?
> > Because-
> > 
> > 1. The range slider limits the users. To give the range from 0 to 400. Whereas the value of the pools can go way beyond.
> > 2. Precicion is not met with range slider. A lot of times the value of pools are in float/decimal values.
> > 
> > Just a thought. I think putting a text box would be better.
> > Or maybe we could keep the range slider and put a text box below that.
> > Cc: @shubhamkarande13
> 
> Great idea. What we do is create a component wrapper with 2 radio based options (custom and range) so that by default users can set a range value, if they want custom then after selecting the custom radio button an input box will appear.
> 
> If this sounds to be a good approach, I can start designing it.

This sounds good. 

Though, we can design the RangeSlider component that accepts props which manage with props such as:
* `customRange` - [x,y] (Array of x and y shows that the slider should range from x to y value)
* `precisionValue` - 0.1 or 0.01 and so on to show the selection precision 
* `step`: how many units are stepped on sliding (as a similar alternative to precisionValue)
* `onChange`: runs a callback function when change is detected in range slider component (optional)

Personally, I find the `RangeSlider` props of [`chakra-ui design system`](https://chakra-ui.com/docs/form/range-slider#rangesliderthumb-props) very well defined and can definitely take inspiration from it.

**Comment by chicken-biryani** [comment] 2021-12-16 08:50
@yashsehgal @sohamsshah 

The problem is that... it limits the user.

The values can go way beyond (negative and positive).....

I don't know whether having a range slider is useful. 😬

**Comment by sohamsshah** [comment] 2021-12-16 08:53
> @yashsehgal @sohamsshah
> 
> The problem is that... it limits the user.
> 
> The values can go way beyond (negative and positive).....
> 
> I don't know whether having a range slider is useful. 😬

If that is the case, then it would be better to take help from designer for the final UI for the requested component. Once it is confirmed, then only it would make sense to actually write code for the component.

**Comment by yashsehgal** [comment] 2021-12-16 09:23
Correct 💯 
Got your points @chicken-biryani @sohamsshah 
I will be working on the component designing part of it and will update you soon. 👍🏽

**Comment by yashsehgal** [comment] 2021-12-17 07:49
I have created a concept wireframe of this component.
- We can have 2 radio buttons to select what kind of values user want to add.
- Slider component can be taken from Chakra UI, as it already have a set of pre-developed logics.
- Input boxes can be added in the `Set custom duration` option.

This is how the design is looking, you can also check it on figma [here](https://www.figma.com/file/AJPJpCqB6L6ikEzooxHa4a/flint-ui-component?node-id=0%3A1)
![image](https://user-images.githubusercontent.com/62352288/146508704-5bd025f5-ca06-4dcc-b88a-727ce0987628.png)

**Comment by yashsehgal** [comment] 2021-12-19 08:16
Hey @chicken-biryani @sohamsshah 
Can I continue with the UI component design above and also, are there any changes required?

**Comment by sohamsshah** [comment] 2021-12-19 08:29
Hey @yashsehgal , this seems great. Sure, please raise a PR for this component, it would be great!

**Comment by yashsehgal** [comment] 2022-01-05 17:04
Hey @sohamsshah 
Sorry for taking so much time on this, but here's a small prototype of this component that I have development code-sandbox

https://codesandbox.io/s/elated-dawn-hhdmz?file=/src/App.vue

If it looks good to you, I can start implementing this feature into our codebase.

Tools I have used: ChakraUI for Vue

**Comment by sohamsshah** [comment] 2022-01-06 05:46
> Hey @sohamsshah Sorry for taking so much time on this, but here's a small prototype of this component that I have development code-sandbox
> 
> https://codesandbox.io/s/elated-dawn-hhdmz?file=/src/App.vue
> 
> If it looks good to you, I can start implementing this feature into our codebase.
> 
> Tools I have used: ChakraUI for Vue
> 
> Here's some SS of the current component design
> 
> * Slider type input
>   ![image](https://user-images.githubusercontent.com/62352288/148258755-d257d4ae-60d7-4361-aba9-5f8b48456ca6.png)
> * Custom input
>   ![image](https://user-images.githubusercontent.com/62352288/148258700-37fe287c-8925-422e-8eb1-5dc5ff9450dc.png)

Hey @yashsehgal , I see that you have used Chakra-UI Vue for this. The implementation looks good but I feel that the decision about the design system is still awaiting (See comments here #136 ) Once it is finalized, we can move forward with this.

**Comment by Palaksharma23** [comment] 2022-03-12 06:10
@sohamsshah i would like to work on this issue :)

**Comment by chicken-biryani** [comment] 2022-03-12 06:41
Hi, @Palaksharma23 we have a new issue with similar instructions but I believe revolving around what we require lately.

I'll close this one.

**Closed** 2022-03-12 06:41 UTC
Labels: enhancement, good first issue, beginner friendly
